from .ConnectionV2 import db

def relatorio_vendedor(dt_inicio, dt_fim, cd_vendedor):
    _querie = f"""
    SELECT
        N.CD_EMPRESA, N.NR_LANCAMENTO, N.CD_SERIE, N.TP_NOTA, N.DT_EMISSAO,
        COALESCE(N.NR_NOTAFISCAL, N.NR_NOTAFOR) NR_NOTA,
        PC.CD_PESSOA, PC.NM_PESSOA, PV.CD_PESSOA CD_VENDEDOR, PV.NM_PESSOA NM_VENDEDOR,
        SUM(COALESCE(PS_ITEMNOTA, IT.QT_ITEMNOTA)) QT_ITEM,SUM(IT.VL_TOTAL) VL_NOTA,
        N.VL_NOTAFISCAL
    FROM
        NOTA N
        INNER JOIN ITEMNOTA IT ON (IT.CD_EMPRESA = N.CD_EMPRESA
            AND IT.NR_LANCAMENTO = N.NR_LANCAMENTO
            AND IT.TP_NOTA = N.TP_NOTA
            AND IT.CD_SERIE = N.CD_SERIE)
        INNER JOIN PESSOA PC ON (PC.CD_PESSOA = N.CD_PESSOA)
        INNER JOIN FORMAPAGTO F ON (N.CD_FORMAPAGTO = F.CD_FORMAPAGTO) 
        INNER JOIN PESSOA PV ON (PV.CD_PESSOA = N.CD_VENDEDOR)
        INNER JOIN MOVIMENTACAO MOV ON (MOV.CD_MOVIMENTACAO = IT.CD_MOVIMENTACAO)
    WHERE
        N.CD_EMPRESA = 52
        AND N.TP_NOTA = 'S'
        AND N.ST_NOTA = 'V'
        AND N.DT_EMISSAO BETWEEN '{dt_inicio}' AND '{dt_fim}'
        AND N.CD_VENDEDOR IN ({cd_vendedor})
        AND MOV.ST_MESTRA = 'N'
        AND MOV.ST_DEVOLUCAO = 'N'
        AND MOV.CD_TIPOCONTA IS NOT NULL
    GROUP BY
        N.CD_EMPRESA, N.NR_LANCAMENTO, N.CD_SERIE, N.TP_NOTA, N.DT_EMISSAO,
        PC.CD_PESSOA, PC.NM_PESSOA, CD_VENDEDOR, NM_VENDEDOR, NR_NOTA,
        N.VL_NOTAFISCAL
    """
    return db.read_sql(query=_querie)

def extend_devolucao(nr_lanc, cd_emp, tp_nota, cd_serie):
    _querie = f"""
    SELECT
        DN.CD_EMPRORIG, DN.NR_LANCTOORIG, DN.TP_NOTAORIG, DN.CD_SERIEORIG,
        DN.CD_EMPRDEST, DN.NR_LANCTODEST, DN.TP_NOTADEST,
        DN.CD_SERIEDEST,SUM(COALESCE(DN.PS_DEVOLUCAO, DN.QT_DEVOLUCAO)) QT_DEVOLUCAO,
        SUM(DN.VL_DEVOLUCAO) VL_DEVOLUCAO, 
        COALESCE(N.NR_NOTAFISCAL, N.NR_NOTAFOR) NR_NOTA,
        N.DT_EMISSAO, N.VL_NOTAFISCAL
    FROM DEVOLUCAONOTA DN
    INNER JOIN NOTA N ON (N.CD_EMPRESA = DN.CD_EMPRDEST
        AND N.NR_LANCAMENTO = DN.NR_LANCTODEST
        AND N.CD_SERIE = DN.CD_SERIEDEST
        AND N.TP_NOTA = DN.TP_NOTADEST)
    WHERE
        DN.CD_EMPRORIG = {cd_emp}
        AND DN.NR_LANCTOORIG = {nr_lanc}
        AND DN.TP_NOTAORIG = '{tp_nota}'
        AND DN.CD_SERIEORIG = '{cd_serie}'
    GROUP BY
        DN.CD_EMPRORIG, DN.NR_LANCTOORIG, DN.TP_NOTAORIG, DN.CD_SERIEORIG,
        DN.CD_EMPRDEST, DN.NR_LANCTODEST, DN.TP_NOTADEST,
        DN.CD_SERIEDEST, NR_NOTA, N.DT_EMISSAO, N.VL_NOTAFISCAL

    """
    return db.read_sql(query=_querie)

def vendedores():
    _querie = """
    SELECT P.CD_PESSOA||' - '||P.NM_PESSOA NM_VENDEDOR
    FROM PESSOA P
    INNER JOIN VENDEDOR V ON (P.CD_PESSOA = V.CD_VENDEDOR)
    WHERE P.ST_ATIVA = 'S'
    AND P.CD_TIPOPESSOA = 5
    """
    return db.read_sql(query=_querie)